In [1]:
import numpy as np

import gym
import gym_tictactoe

from agents.SearchAgent import RandomAgent
from agents.SearchAgent import UserAgent
from agents.SearchAgent import MinimaxAgent

In [2]:
agents = []
agents.append(UserAgent("Michael", "X"))
agents.append(MinimaxAgent("Bot", "O", 9))

In [3]:
env = gym.make('tictactoe-v0', dim=3)

for agent in agents:
    env.register_agent(agent)
    
agents[1].assign_env(env)
agents[1].assign_opsign(agents[0].sign)

In [4]:
board = np.array([[1,2,2],[2,1,1],[1,2,2]]) #draw
board = np.array([[1,2,1],[0,2,1],[2,0,1]]) #loss
reward = env.state_reward(board, agents[1])
print(reward)

-1


In [5]:
env.render()
done = False
while not done:
    for agent in agents:
        pos = agent.choose(env.board)
        action = [pos, agent]
        reward, done = env.step(action)
        env.render()
        print("="*5)
        if done: break
        
print("{} won!".format(env.winner))
env.reset()

---
---
---
Choose a location in the form (x,y):(0,0)
X--
---
---
=====
[[1. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 2.]
 [0. 0. 0.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]
Value of this option: 0.5
[[1. 0. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 0.]
 [0. 0. 0.]
 [2. 0. 0.]]
Value of this option: -1
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 2. 0.]]
Value of this option: -1
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 2.]]
Value of this option: -1
X--
-O-
---
=====
Choose a location in the form (x,y):(2,0)
X-X
-O-
---
=====
[[1. 2. 1.]
 [0. 2. 0.]
 [0. 0. 0.]]
Value of this option: 0.5
[[1. 0. 1.]
 [2. 2. 0.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 1.]
 [0. 2. 2.]
 [0. 0. 0.]]
Value of this option: -1
[[1. 0. 1.]
 [0. 2. 0.]
 [2. 0. 0.]]
Value of this option: -1
[[1. 0. 1.]
 [0. 2. 0.]
 [0. 2. 0.]]
Value of this option: -1
[[1. 0. 1.]
 [0. 2. 0.]
 [0. 0. 2.]]
Value