In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
class Env:
    def __init__(self, length, width):
        self.board = np.zeros((width, length))
        
    def victory_condition(self):
        
    def step(self, action):
        if action:
            x,y = action.position
            self.board[x,y] = action.actor.sign
    
    def __repr__(self):
        return str(self.board)

In [4]:
class Agent:    
    def __init__(self, name, sign):
        self.name = name
        self.sign = sign
        
    def move(self, board):
        for w in range(board.shape[0]):
            for l in range(board.shape[1]):
                if board[w][l] == 0:
                    return Action(self, (w,l))
        
    def __repr__(self):
        return self.name

In [5]:
agent_1 = Agent("Bob", 1)
agent_2 = Agent("Milo", -1)

env = Env(3,3)

In [6]:
print(env)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
for i in range(5):
    action1 = agent_1.move(env.board)
    env.step(action1)

    action2 = agent_2.move(env.board)
    env.step(action2)
    print(env)

[[ 1. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1. -1.  1.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 0.  0.  0.]]
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  0.]]
[[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]
